/* utf.c - UTF-8 support code
;
; Copyright (c) 2022-2022, The CHICKEN Team
; All rights reserved.
;
; Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
; conditions are met:
;
;   Redistributions of source code must retain the above copyright notice, this list of conditions and the following
;     disclaimer.
;   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
;     disclaimer in the documentation and/or other materials provided with the distribution.
;   Neither the name of the author nor the names of its contributors may be used to endorse or promote
;     products derived from this software without specific prior written permission.
;
; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
; OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
; AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
; CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
; CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
; SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
; THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
; OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
; POSSIBILITY OF SUCH DAMAGE.
*/


#include "chicken.h"

#if defined(_WIN32) && !defined(__CYGWIN__)
# include <windows.h>
#endif

/* The comparison helpers below and the layout of the tables they search
   are inspired by http://git.suckless.org/ubase/; see LICENSE for more
   information.

   The tables are now generated by scripts/mkunicodetables.scm from the Unicode
   character database. */

#define nelem(x)  (sizeof (x) / sizeof *(x))

/* Hacker's Delight, 2-nd edition; 4-1 Checking bounds of integers.
   Compiles to branchless code on ARM64 and x86-64. */
static int
rune2cmp(const void *v1, const void *v2)
{
	int r = *(const int *)v1;
	const int *p = (const int *)v2;
        int d = r - p[0];

        /* Signed overflow is UB, but the range of Unicode codepoints
           is way smaller than the range of int32. */
	if ((unsigned)d <= (unsigned)(p[1] - p[0]))
		return 0;

	return d;
}

static int
runemapcmp(const void *v1, const void *v2)
{
	return *(int *)v1 - *(int *)v2;
}

#include "utf-tables.c"

/* Is rune r in set? */
static int
in_set(int r, const int (*set)[2], int n)
{
	return bsearch(&r, set, n, sizeof *set, &rune2cmp) != NULL;
}

/* Map rune r using map; return unchanged if not in map. */
static int
mapped(int r, const int (*map)[3], int n)
{
	const int *m = bsearch(&r, map, n, sizeof *map, &rune2cmp);

	return m == NULL ? r : m[2] + (r - m[0]);
}

/* As per R7RS 6.6 */
C_regparm int C_utf_isalpha(int r) { return in_set(r, alpha, nelem(alpha)); }
C_regparm int C_utf_isupper(int r) { return in_set(r, upper, nelem(upper)); }
C_regparm int C_utf_islower(int r) { return in_set(r, lower, nelem(lower)); }
C_regparm int C_utf_isspace(int r) { return in_set(r, space, nelem(space)); }

C_regparm int C_utf_char_upcase(int r) { return mapped(r, uppermap, nelem(uppermap)); }
C_regparm int C_utf_char_downcase(int r) { return mapped(r, lowermap, nelem(lowermap)); }

/* Return rune r decimal digit value + 1, or 0 if not a decimal digit. */
C_regparm int C_utf_isdigit(int r)
{
	const int *d = bsearch(&r, digit, nelem(digit), sizeof *digit, &rune2cmp);

	return d == NULL ? 0 : 1 + (r - d[0]);
}


/* Branchless UTF-8 decoder
 * https://raw.githubusercontent.com/skeeto/branchless-utf8/
 * This is free and unencumbered software released into the public domain.
 */

/* Decode the next character, C, from BUF, reporting errors in E.
 *
 * Since this is a branchless decoder, four bytes will be read from the
 * buffer regardless of the actual length of the next character. This
 * means the buffer _must_ have at least three bytes of zero padding
 * following the end of the data stream.
 *
 * Errors are reported in E, which will be non-zero if the parsed
 * character was somehow invalid: invalid byte sequence, non-canonical
 * encoding, or a surrogate half.
 *
 * The function returns a pointer to the next character. When an error
 * occurs, this pointer will be a guess that depends on the particular
 * error, but it will always advance at least one byte.
 */

/* (flw) quite modified and doubtlessly less branchless and optimized
   as the original. */

static const char lengths[] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 3, 4, 0
};

static C_char *utf8_decode(C_char *buf, C_u32 *c, int *e)
{
    static const int masks[]  = {0x00, 0x7f, 0x1f, 0x0f, 0x07};
    static const uint32_t mins[] = {4194304, 0, 128, 2048, 65536};
    static const int shiftc[] = {0, 18, 12, 6, 0};
    static const int shifte[] = {0, 6, 4, 2, 0};

#ifdef DEBUGBUILD
    if(buf == NULL)
        C_panic_hook(C_text("possibly invalid string index"));
#endif

    unsigned char *s = (unsigned char *)buf;
    int len = lengths[s[0] >> 3];

    /* Compute the pointer to the next character early so that the next
     * iteration can start working on the next character. Neither Clang
     * nor GCC figure out this reordering on their own.
     */
    unsigned char *next = s + len + !len;

    /* Assume a four-byte character and load four bytes. Unused bits are
     * shifted out.
     */
    *c  = (C_u32)(s[0] & masks[len]) << 18;
    *c |= (C_u32)(s[1] & 0x3f) << 12;
    *c |= (C_u32)(s[2] & 0x3f) <<  6;
    *c |= (C_u32)(s[3] & 0x3f) <<  0;
    *c >>= shiftc[len];

    /* Accumulate the various error conditions. */
    *e  = (*c < mins[len]) << 6; // non-canonical encoding
    *e |= ((*c >> 11) == 0x1b) << 7;  // surrogate half?
    *e |= (*c > 0x10FFFF) << 8;  // out of range?
    *e |= (s[1] & 0xc0) >> 2;
    *e |= (s[2] & 0xc0) >> 4;
    *e |= (s[3]       ) >> 6;
    *e ^= 0x2a; // top two bits of each tail byte correct?
    *e >>= shifte[len];

    /* now make all that optimization pointless... */
    if(*e) {
        *c = 0xdc00 | *s;
        return (C_char *)s + 1;
    }

    return (C_char *)next;
}
/* */

static C_char *utf8_encode(C_u32 u, C_char *p1)
{
    unsigned char *p = (unsigned char *)p1;
    if(u < 0x80) *(p++) = u;
    else if((u & 0xff00) == 0xdc00) {
        *(p++) = u & 0xff;
    } else if(u < 0x800) {
        *(p++) = (u >> 6) | 0xC0;
        *(p++) = (u & 0x3F) | 0x80;
    } else if(u < 0x10000) {
        *(p++) = (u >> 12) | 0xE0;
        *(p++) = ((u >> 6) & 0x3F) | 0x80;
        *(p++) = (u & 0x3F) | 0x80;
    } else if(u < 0x110000) {
        *(p++) = (u >> 18) | 0xF0;
        *(p++) = ((u >> 12) & 0x3F) | 0x80;
        *(p++) = ((u >> 6) & 0x3F) | 0x80;
        *(p++) = (u & 0x3F) | 0x80;
    }
    return (C_char *)p;
}

static C_char *utf_index1(C_word s, C_word i)
{
    C_word i0 = C_unfix(C_block_item(s, 2));
    C_word count = C_unfix(C_block_item(s, 1));
    C_word off = 0, index = 0;
    C_char *p1, *p = C_c_string(C_block_item(s, 0));
    int e;
    C_u32 c;
    if(i >= i0) {
        p += off = C_unfix(C_block_item(s, 3));
        index = i0;
    }
    while(index <= count) {
        if(index == i) {
            C_set_block_item(s, 2, C_fix(index));
            C_set_block_item(s, 3, C_fix(off));
            return p;
        }
        p1 = p;
        p = utf8_decode(p, &c, &e);
        ++index;
        off += p - p1;
    }
    return NULL;
}

static C_char *utf_index(C_word s, C_word i)
{
    C_word bv = C_block_item(s, 0);
    if(i == 0) {
        C_set_block_item(s, 2, C_fix(0));
        C_set_block_item(s, 3, C_fix(0));
        return C_c_string(bv);
    } else if(C_header_size(bv) - 1 == C_unfix(C_block_item(s, 1))) {
        /* len == codepoints */
        C_set_block_item(s, 2, C_fix(i));
        C_set_block_item(s, 3, C_fix(i));
        return C_c_string(bv) + i;
    }
    return utf_index1(s, i);
}

C_regparm C_word C_utf_subchar(C_word s, C_word i)
{
    C_char *p = utf_index(s, C_unfix(i));
    int e;
    C_u32 c;
    utf8_decode(p, &c, &e);
    return C_make_character(c);
}

C_regparm C_word C_utf_setsubchar(C_word s, C_word i, C_word c)
{
    C_char buf[ 4 ];
    C_char *p = utf8_encode(C_character_code(c), buf);
    int e;
    C_u32 old;
    C_char *p1 = utf_index(s, C_unfix(i));
    C_char *p2 = utf8_decode(p1, &old, &e);
    int nl = p - buf, ol = p2 - p1;
    C_word bv = C_block_item(s, 0);
    C_word bvlen = C_header_size(bv) - 1;
    int prefix = C_unfix(C_block_item(s, 3));    /* offset */
    int suffix = bvlen - prefix - ol;

    if(nl > ol) {
        int tl = bvlen + nl - ol;
        /* C_scratch_alloc() may resize the scratch space: that moves every
           scratch object whose owning slot is registered and frees the old
           space.  So `bv' (the result of an earlier string-set! that grew
           this string) must stay registered until the allocation is done
           and must be re-read from the string afterwards; unregistering it
           first, as was done before, left us copying from freed memory. */
        C_word bvn = C_scratch_alloc(C_SIZEOF_BYTEVECTOR(tl + 1));
        bv = C_block_item(s, 0);
        if(C_in_scratchspacep(bv)) C_mutate_scratch_slot(NULL, bv);
        C_block_header_init(bvn, C_make_header(C_BYTEVECTOR_TYPE, tl + 1));
        if(prefix) C_memcpy(C_c_string(bvn), C_c_string(bv), prefix);
        C_memcpy((C_char *)C_data_pointer(bvn) + prefix, buf, nl);
        C_memcpy((C_char *)C_data_pointer(bvn) + prefix + nl,
            (C_char *)C_data_pointer(bv) + prefix + ol, suffix + 1); /* include 0 byte */
        C_mutate_slot(&C_block_item(s, 0), bvn);
        C_mutate_scratch_slot(&C_block_item(s, 0), bvn);
    } else if(nl < ol) {
        C_memcpy(p1, buf, nl);
        C_memmove(p1 + nl, p1 + ol, suffix + 1); /* include 0 byte */
        C_block_header_init(bv, C_make_header(C_BYTEVECTOR_TYPE, bvlen - (ol - nl) + 1));
    } else C_memcpy(p1, buf, nl);

    return C_SCHEME_UNDEFINED;
}

/* copy c bytes of bv into s at position i, occupying len characters */
C_regparm C_word C_utf_overwrite(C_word s, C_word i, C_word len, C_word bv,
    C_word c)
{
    C_word bvs = C_block_item(s, 0);
    C_word bvlen = C_header_size(bvs) - 1;
    C_char *p1 = utf_index(s, C_unfix(i));
    C_char *p2 = utf_index(s, C_unfix(i) + C_unfix(len));
    int count = C_unfix(c);
    int d = p2 - p1;
    int prefix = p1 - (C_char *)C_data_pointer(bvs);
    int suffix = bvlen - prefix - d;

    if(count > d) {
        int tl = bvlen + count - d;
        /* C_scratch_alloc() may move `bvs' if it lives in scratch space
           (see C_utf_setsubchar): re-read it and recompute `p2'. */
        C_word bvn = C_scratch_alloc(C_SIZEOF_BYTEVECTOR(tl + 1));
        bvs = C_block_item(s, 0);
        p2 = (C_char *)C_data_pointer(bvs) + prefix + d;
        if(C_in_scratchspacep(bvs)) C_mutate_scratch_slot(NULL, bvs);
        C_block_header_init(bvn, C_make_header(C_BYTEVECTOR_TYPE, tl + 1));
        if(prefix) C_memcpy(C_c_string(bvn), C_data_pointer(bvs), prefix);
        C_memcpy((C_char *)C_data_pointer(bvn) + prefix, (C_char *)C_data_pointer(bv),
            count);
        C_memcpy((C_char *)C_data_pointer(bvn) + prefix + count,
            p2, suffix + 1); /* include 0 byte */
        C_mutate_slot(&C_block_item(s, 0), bvn);
        C_mutate_scratch_slot(&C_block_item(s, 0), bvn);
    } else if(count < d && count) {
        C_memcpy(p1, C_data_pointer(bv), count);
        C_memmove(p1 + count, p2, suffix + 1); /* include 0 byte */
        C_block_header_init(bvs, C_make_header(C_BYTEVECTOR_TYPE,
            bvlen - (d - count) + 1));
    } else if(count) C_memcpy(p1, C_data_pointer(bv), count);

    return C_SCHEME_UNDEFINED;
}

C_regparm C_word C_utf_set_bv_size(C_word bv, C_word sz)
{
    int i = C_unfix(sz);
    C_block_header_init(bv, C_make_header(C_BYTEVECTOR_TYPE, i + 1));
    C_char *p = (C_char *)C_data_pointer(bv);
    p[ i ] = 0;
    return bv;
}

C_regparm C_word C_utf_compare(C_word s1, C_word s2, C_word start1, C_word start2,
    C_word len)
{
    C_char *p1 = utf_index(s1, C_unfix(start1));
    C_char *p2 = utf_index(s2, C_unfix(start2));
    int e, n = C_unfix(len);

    /* ASCII fast path.  While both current bytes are < 0x80 each one is a
     * whole character whose codepoint is the byte itself (see the
     * derivation above C_utf_count), so comparing bytes is the same
     * comparison the decode loop below performs, down to the value
     * returned.  `len' counts characters, not bytes, and an ASCII
     * character is one byte, so consuming one byte per iteration keeps
     * `n' meaning what it means in the general loop.  The moment either
     * side is non-ASCII we drop into that loop at the very position we
     * reached and nothing is lost.
     *
     * Deliberately a byte loop and not C_memcmp or a SWAR word compare:
     * the character counts that reach here are tiny.  An instrumented
     * count of every call made while compiling library.scm saw 393216 of
     * them with a maximum `len' of 7 and 93% at len == 2, and at two
     * characters memcmp's call and setup cost more than the two loads it
     * replaces.
     */
    while(n > 0) {
        unsigned char b1 = (unsigned char)*p1, b2 = (unsigned char)*p2;
        if((b1 | b2) & 0x80) break;
        if(b1 != b2) return C_fix((C_word)b1 - (C_word)b2);
        ++p1; ++p2; --n;
    }

    while(n--) {
        C_u32 c1, c2;
        p1 = utf8_decode(p1, &c1, &e);
        p2 = utf8_decode(p2, &c2, &e);
        if(c1 != c2) return C_fix((C_word)c1 - (C_word)c2);
    }
    return C_fix(0);
}

typedef struct C_fold {
    C_char *p; /* Pointer to the beginning of the next UTF-8 char. */
    int n;     /* Number of remaining UTF-8 chars. */
    int i;     /* Start index of the buffer. */
    int e;     /* End index of the buffer. */
    int b[3];
} C_FOLD;

#define C_fold_empty(r) ((r).i == (r).e)
#define C_fold_len(r) ((r).e - (r).i)
#define C_fold_push(r, c) ((r).b[ (r).e++ ] = (c))
#define C_fold_pop(r) ((r).b[ (r).i++ ])
#define C_fold_more(r) ((r).n || !C_fold_empty(r))

C_regparm C_word C_utf_compare_ci(C_word s1, C_word s2, C_word start1, C_word start2, C_word len1, C_word len2)
{
    /* The lengths of strings and indices into them are meaningless to us
       (besides bounding the slice of input we are looking into), because the
       length of a folded string may be anywhere between N and 3*N. Instead we
       maintain two lookahead buffers of capacity 3. The buffers are refilled
       when they run empty, and are consumed by one rune at each iteration. */
    C_FOLD f[2] = {
        {.p = utf_index(s1, C_unfix(start1)), .n = C_unfix(len1), .i = 0, .e = 0, .b = {0}},
        {.p = utf_index(s2, C_unfix(start2)), .n = C_unfix(len2), .i = 0, .e = 0, .b = {0}}};
    while(C_fold_more(f[0]) && C_fold_more(f[1])) {
        int r1 = (unsigned char)*f[0].p, r2 = (unsigned char)*f[1].p;
        /* 7-bit ASCII fast path. */
        if(!((r1 | r2) & 0x80) && C_fold_empty(f[0]) && C_fold_empty(f[1])) {
            if(r1 >= 'A' && r1 <= 'Z') r1 += 32;
            if(r2 >= 'A' && r2 <= 'Z') r2 += 32;
            if(r1 != r2) return C_fix(r1 - r2);
            f[0].p++; f[1].p++;
            f[0].n--; f[1].n--;
            continue;
        }
        /* At least one UTF-8 rune or unconsumed fold, slow path. */
        for(int i = 0; i < 2; i++) {
            if(C_fold_empty(f[i])) {
                /* Refill buffers and advance n. */
                C_u32 c; int u; int err; const int *m;
                f[i].i = f[i].e = 0;
                f[i].p = utf8_decode(f[i].p, &c, &err); f[i].n--; u = c;
                m = bsearch(&u, fold2, nelem(fold2), sizeof(*fold2), &runemapcmp);
                if(m) {
                    for(int j = 1; j <= 3; ++j) {
                        if(!m[j]) break;
                        C_fold_push(f[i], m[j]);
                    }
                } else {
                    m = bsearch(&u, fold1, nelem(fold1), sizeof(*fold1), &runemapcmp);
                    if(m) C_fold_push(f[i], m[1]);
                    else C_fold_push(f[i], u);
                }
            }
        }
        /* Now runes in b at i can be directly compared. */
        r1 = C_fold_pop(f[0]);
        r2 = C_fold_pop(f[1]);
        if(r1 != r2) return C_fix(r1 - r2);
    }
    /* Everything matched up to this point, the shortest string wins. */
    return C_fix((f[0].n + C_fold_len(f[0])) - (f[1].n + C_fold_len(f[1])));
}

/* XXX inline this? */
C_regparm C_word C_utf_equal(C_word s1, C_word s2)
{
    C_word b1 = C_block_item(s1, 0);
    C_word b2 = C_block_item(s2, 0);
    int n1 = C_header_size(b1);
    int n2 = C_header_size(b2);
    if(n1 != n2) return C_SCHEME_FALSE;
    return C_mk_bool(C_memcmp(C_c_string(b1), C_c_string(b2), n1) == 0);
}

/* XXX inline this? */
C_regparm C_word C_utf_equal_ci(C_word s1, C_word s2)
{
    return C_mk_bool(C_utf_compare_ci(s1, s2, C_fix(0), C_fix(0),
                                      C_block_item(s1, 1), C_block_item(s2, 1)) == C_fix(0));
}

C_regparm C_word C_utf_copy(C_word from, C_word to, C_word start1, C_word end1, C_word start2)
{
    C_char *p1 = utf_index(from, C_unfix(start1));
    C_char *p2 = utf_index(to, C_unfix(start2));
    C_char *p3 = utf_index(from, C_unfix(end1));
    C_memcpy(p2, p1, p3 - p1);
    return C_SCHEME_UNDEFINED;
}

/* compute byte-index from char-index */
C_regparm C_word C_utf_position(C_word str, C_word index)
{
    C_char *p1 = utf_index(str, C_unfix(index));
    return C_fix(p1 - C_c_string(C_block_item(str, 0)));
}

/* compute char-index from byte-index (slow, uncached) */
C_regparm int C_utf_char_position(C_word bv, int pos)
{
    int p = 0;
    C_u32 c;
    int e;
    C_char *ptr = C_c_string(bv), *ptr2;
    while(pos > 0) {
        ptr2 = utf8_decode(ptr, &c, &e);
        pos -= ptr2 - ptr;
        ptr = ptr2;
        ++p;
    }
    return p;
}

/* compute byte-offset between two char-indices */
C_regparm C_word C_utf_range(C_word str, C_word start, C_word end)
{
    C_char *p1 = utf_index(str, C_unfix(start));
    /* utf_index() has just memoised (start, byte-offset-of-start) in slots
     * 2 and 3.  Indexing `end' below overwrites that with (end, ...), which
     * throws away the only cursor a caller can use.  ##sys#substring is
     * exactly such a caller: it calls this and then C_utf_copy, which
     * indexes `start' again - and `start' < `end' means utf_index1() cannot
     * use the memo and rescans from the head of the string.  Ascending
     * tokenisation of a string with even one non-ASCII character therefore
     * costs O(n^2).  Save the cursor and put it back, so the memo still
     * describes `start' when this returns.
     *
     * MEASURED, and less than was first claimed for it: this removes ONE of
     * the two head-scans ##sys#substring performs per call, so it is worth a
     * flat 2.0x and NOT the complexity fix it was originally reported as.
     * Ascending (substring s i (+ i 5)) over a string whose first character
     * is non-ASCII, best of 3, identical -O3 binaries against each library:
     *
     *     n         before      after
     *     10001      648 ms     324 ms
     *     20001     2570       1294
     *     40001    10289       5175
     *     80001    41138      20704
     *    160001   164513      82765
     *
     * Both columns still quadruple per doubling, i.e. both are still O(n^2);
     * only the constant halves.  The remaining scan is the utf_index(start)
     * on the line above, which still misses the memo across calls.  Making
     * that one hit as well is the change that would actually make ascending
     * tokenisation linear, and it has not been made.
     */
    C_word i0 = C_block_item(str, 2), off = C_block_item(str, 3);
    C_char *p2 = utf_index(str, C_unfix(end));
    C_set_block_item(str, 2, i0);
    C_set_block_item(str, 3, off);
    return C_fix(p2 - p1);
}

/* Count characters - slow variant, handles invalid sequences.
 *
 * This counts codepoints without calling utf8_decode(), because it needs
 * only the advance, never the codepoint itself.  It is bit-exact with the
 * decoder-driven loop it replaces; the two facts it rests on are derived
 * from utf8_decode()'s error algebra above:
 *
 *  - For a byte < 0x80, lengths[b >> 3] == 1, so *e is shifted right by
 *    shifte[1] == 6.  Before that shift *e only ever has bits 0..5 set
 *    (bit 6 needs *c < mins[1] == 0, bit 7 needs a surrogate and bit 8 a
 *    value > 0x10FFFF, and *c is just s[0] & 0x7f here), so *e == 0 no
 *    matter what s[1..3] hold: an ASCII byte always advances by exactly
 *    one and never errors.  That makes a run of ASCII bytes countable
 *    eight at a time with a SWAR test for any high bit.
 *
 *  - For a lead byte the advance is lengths[b >> 3] when *e == 0 and 1
 *    otherwise.  Solving *e == 0 for each length (only the bits that
 *    survive the >>= shifte[len] matter) gives:
 *      len 2: (s[1] & 0xc0) == 0x80             [tail byte]
 *             && b >= 0xc2                      [*c >= mins[2] == 128]
 *      len 3: (s[1] & 0xc0) == 0x80 && (s[2] & 0xc0) == 0x80
 *             && !(b == 0xe0 && s[1] < 0xa0)    [*c >= mins[3] == 2048]
 *             && !(b == 0xed && s[1] >= 0xa0)   [(*c >> 11) != 0x1b]
 *      len 4: (s[1] & 0xc0) == 0x80 && (s[2] & 0xc0) == 0x80
 *             && (s[3] & 0xc0) == 0x80
 *             && !(b == 0xf0 && s[1] < 0x90)    [*c >= mins[4] == 65536]
 *             && (b < 0xf4 || (b == 0xf4 && s[1] < 0x90))  [*c <= 0x10FFFF]
 *      len 0: a stray 0x80..0xbf or 0xf8..0xff; *c < mins[0] always holds,
 *             so *e != 0 and the advance is 1 - such a byte still counts
 *             as one character, exactly as utf8_decode()'s error return
 *             makes it.
 *    The surrogate test is subsumed by the minimum test for len 4, and
 *    the range test cannot fire for len 2 or 3, so each length needs only
 *    the conditions listed.
 *
 * Verified by exhaustive differential testing against the decoder-driven
 * loop over all 2^32 four-byte inputs, all 2^24 three-byte inputs at every
 * truncation and four padding patterns, every valid codepoint at sixteen
 * alignments and every truncation, and randomised buffers: 4584928586
 * comparisons, zero disagreements.
 *
 * Note the reads of s[1..3]: they are the same bytes utf8_decode() reads
 * (it loads all four unconditionally), so this looks no further past `len'
 * than the code it replaces - and for a two-byte lead it looks less far.
 */
C_regparm int C_utf_count(C_char *str, int len)
{
    unsigned char *s = (unsigned char *)str;
    int i = 0;

    while(len > 0) {
        unsigned int b = *s;

        if(b < 0x80) {
            /* ASCII run: eight bytes at a time.  memcpy(), not a pointer
               cast, so this stays correct without -fno-strict-aliasing. */
            while(len >= 8) {
                C_u64 w;
                C_memcpy(&w, s, sizeof(w));
                if(w & (C_u64)0x8080808080808080ULL) break;
                s += 8; len -= 8; i += 8;
            }
            while(len > 0 && *s < 0x80) { ++s; --len; ++i; }
        } else {
            int n = lengths[b >> 3];
            switch(n) {
            case 2:
                if(b < 0xc2 || (s[1] & 0xc0) != 0x80) n = 1;
                break;
            case 3:
                if((s[1] & 0xc0) != 0x80 || (s[2] & 0xc0) != 0x80 ||
                   (b == 0xe0 && s[1] < 0xa0) ||
                   (b == 0xed && s[1] >= 0xa0)) n = 1;
                break;
            case 4:
                if((s[1] & 0xc0) != 0x80 || (s[2] & 0xc0) != 0x80 ||
                   (s[3] & 0xc0) != 0x80 ||
                   (b == 0xf0 && s[1] < 0x90) ||
                   b > 0xf4 || (b == 0xf4 && s[1] >= 0x90)) n = 1;
                break;
            default:            /* n == 0: stray tail byte or 0xf8..0xff */
                n = 1;
                break;
            }
            s += n; len -= n; ++i;
        }
    }
    return i;
}

/* Count characters - slow variant, detects invalid sequences */
C_regparm C_word C_utf_validate(C_word bv, C_word blen, C_word start, C_word end)
{
    int i = 0;
    C_u32 c;
    int e;
    unsigned char *s = (unsigned char *)C_c_string(bv) + C_unfix(start), *s2;
    int len = C_unfix(end) - C_unfix(start);
    while (len > 0) {
        if(*s >= 0x80 && *s <= 0xbf) return C_SCHEME_FALSE;
        if(lengths[*s >> 3] > len) return C_SCHEME_FALSE;
        s2 = (unsigned char *)utf8_decode((C_char *)s, &c, &e);
        if(e) return C_SCHEME_FALSE;
        len -= (s2 - s);
        s = s2;
        i++;
    }
    return C_fix(i);
}

/* count characters, fast, unsafe variant
   http://canonical.org/~kragen/strlen-utf8.html */
C_regparm int C_utf_fast_count(C_char *s, int len)
{
    int i = 0, j = 0;
    while (len--) {
        if ((s[i] & 0xc0) != 0x80) j++;
        i++;
    }
    return j;
}

C_regparm C_word C_utf_bytes(C_word chr)
{
    int e;
    char buf[ 5 ];
    C_char *p1 = utf8_encode(C_character_code(chr), buf);
    return C_fix(p1 - buf);
}

C_regparm C_char * C_utf_encode(C_char *str, int chr)
{
    return utf8_encode(chr, str);
}

C_regparm C_word C_utf_decode(C_word bv, C_word pos)
{
    C_u32 c;
    int e;
    utf8_decode(C_c_string(bv) + C_unfix(pos), &c, &e);
    return C_make_character(c);
}

C_regparm C_word C_utf_decode_ptr(C_char *bv)
{
    C_u32 c;
    int e;
    utf8_decode(bv, &c, &e);
    return C_make_character(c);
}

C_regparm C_word C_utf_advance(C_word bv, C_word pos)
{
    C_char *p1 = (C_char *)C_data_pointer(bv) + C_unfix(pos);
    C_u32 c;
    int e;
    C_char *p2 = utf8_decode(p1, &c, &e);
    return C_fix(C_unfix(pos) + p2 - p1);
}

C_regparm C_word C_utf_insert(C_word bv, C_word pos, C_word c)
{
    C_char *p1 = C_c_string(bv) + C_unfix(pos);
    C_char *p2 = utf8_encode(C_character_code(c), p1);
    return C_fix(C_unfix(pos) + p2 - p1);
}

C_regparm C_word C_utf_fill(C_word bv, C_word chr)
{
    char buf[ 5 ];
    int size = C_header_size(bv) - 1;
    int len = C_utf_encode(buf, C_character_code(chr)) - buf;
    C_char *p;
    int n;

    if(len == 1) {
        C_memset(C_data_pointer(bv), *buf, size);
        return bv;
    }

    p = C_data_pointer(bv);
    n = size / len;

    while(n--) {
        C_memcpy(p, buf, len);
        p += len;
    }
    ((C_char *)C_data_pointer(bv))[ size ] = 0; /* terminating zero */
    return bv;
}

C_regparm int C_utf_expect(int byte)
{
    int len = lengths[ byte >> 3 ];
    return len + !len;
}

/* take bytevector section and compute full + incomplete codepoints */
C_regparm C_word C_utf_fragment_counts(C_word bv, C_word pos, C_word len)
{
    int full = 0;
    C_uchar *ptr = C_data_pointer(bv) + C_unfix(pos);
    int count = C_unfix(len);

    while(count) {
        unsigned int byte = *(ptr++);
        int n = lengths[ byte >> 3 ];
        int bn = n + !n;
        if(count >= bn) {
            ++full;
            count -= bn;
            ptr += bn - 1;
        } else return C_fix((full << 4) | (bn - count));
    }

    return C_fix(full << 4);
}

C_regparm void C_utf_putc(int chr, C_FILEPTR fp)
{
    C_char buf[ 5 ];
    C_char *p = utf8_encode(chr, buf);
    *p = '\0';
    C_fputs(buf, fp);
}

C_regparm C_word C_utf_list_size(C_word lst)
{
    int n = 0;
    while(!C_immediatep(lst) && C_header_bits(lst) == C_PAIR_TYPE) {
        C_word x = C_block_item(lst, 0);
        if(((x) & C_IMMEDIATE_TYPE_BITS) == C_CHARACTER_BITS)
            n += C_unfix(C_utf_bytes(x));
        lst = C_block_item(lst, 1);
    }
    return C_fix(n);
}

C_regparm C_word C_latin_to_utf(C_word from, C_word to, C_word start, C_word len)
{
    int n = C_unfix(len);
    C_uchar *pf = (C_uchar *)C_c_string(from) + C_unfix(start);
    C_char *pt = C_c_string(to), *pt0 = pt;
    while(n-- > 0) {
        C_u32 c = *(pf++);
        pt = utf8_encode(c, pt);
    }
    return C_fix(pt - pt0);
}

C_regparm C_word C_utf_to_latin(C_word from, C_word to, C_word start, C_word blen)
{
    int n = C_unfix(blen);
    C_char *pf = C_c_string(from) + C_unfix(start), *pf2;
    C_char *pt = C_c_string(to), *pt0 = pt;
    C_u32 c;
    int e;
    while(n > 0) {
        pf2 = utf8_decode(pf, &c, &e);
        if(c > 255) C_encoding_error(from, C_fix(C_unfix(start) + C_unfix(blen) - n));
        n -= pf2 - pf;
        pf = pf2;
        *(pt++) = c & 0xff;
    }
    *pt = '\0';
    return C_fix(pt - pt0);
}

C_regparm C_word C_utf_char_foldcase(C_word c)
{
    int r = C_character_code(c);
    const int *m = bsearch(&r, fold1, nelem(fold1), sizeof(*fold1), &runemapcmp);
    if(m) return C_make_character(m[ 1 ]);
    return c;
}

C_regparm C_word C_utf_string_foldcase(C_word from, C_word to, C_word len)
{
    C_u32 c;
    int e;
    C_char *pf = C_c_string(from), *pf2;
    C_char *pt = C_c_string(to), *pt0 = pt;
    int count = C_unfix(len);
    while(count > 0) {
        pf2 = utf8_decode(pf, &c, &e);
        if(!e) {
            int r = c;
            const int *m = bsearch(&r, fold2, nelem(fold2), sizeof(*fold2), &runemapcmp);
            if(m) {
                pt = utf8_encode(m[ 1 ], pt);
                if(m[ 3 ] != 0) {
                    pt = utf8_encode(m[ 2 ], pt);
                    c = m[ 3 ];
                } else c = m[ 2 ];
            } else {
                m = bsearch(&r, fold1, nelem(fold1), sizeof(*fold1), &runemapcmp);
                if(m) c = m[ 1 ];
            }
        }
        pt = utf8_encode(c, pt);
        count -= pf2 - pf;
        pf = pf2;
    }
    return C_fix(pt - pt0);
}

C_regparm C_word C_utf_string_downcase(C_word from, C_word to, C_word len)
{
    C_u32 c;
    int e;
    C_char *pf = C_c_string(from), *pf2;
    C_char *pt = C_c_string(to), *pt0 = pt;
    int count = C_unfix(len);
    while(count > 0) {
        pf2 = utf8_decode(pf, &c, &e);
        if(!e) c = C_utf_char_downcase(c);
        pt = utf8_encode(c, pt);
        count -= pf2 - pf;
        pf = pf2;
    }
    return C_fix(pt - pt0);
}

C_regparm C_word C_utf_string_upcase(C_word from, C_word to, C_word len)
{
    C_u32 c;
    int e;
    C_char *pf = C_c_string(from), *pf2;
    C_char *pt = C_c_string(to), *pt0 = pt;
    int count = C_unfix(len);
    while(count > 0) {
        pf2 = utf8_decode(pf, &c, &e);
        if(!e) c = C_utf_char_upcase(c);
        pt = utf8_encode(c, pt);
        count -= pf2 - pf;
        pf = pf2;
    }
    return C_fix(pt - pt0);
}

#if defined(_WIN32) && !defined(__CYGWIN__)
#define C_WCHAR_FNBUF_SIZE	2048
static C_WCHAR fnbuf[ C_WCHAR_FNBUF_SIZE ], *pfnbuf;
C_regparm C_WCHAR *C_utf16(C_word bv, int cont)
{
	int len = C_header_size(bv) - 1;
	C_WCHAR *p;
	if(!cont) pfnbuf = fnbuf;
	p = pfnbuf;
	int n = MultiByteToWideChar(CP_UTF8,
		0,
		C_c_string(bv),
		-1,
		pfnbuf,
		C_WCHAR_FNBUF_SIZE - (pfnbuf - fnbuf));
	if(n == 0) C_decoding_error(bv, C_fix(0));
	pfnbuf += n;
	return p;
}

C_regparm C_char *C_utf8(C_WCHAR *str)
{
	int n = WideCharToMultiByte(CP_UTF8,
		0,
		str,
		-1,
		(C_char *)fnbuf,
		C_WCHAR_FNBUF_SIZE,
		NULL, NULL);
	if(n == 0) C_decoding_error(C_SCHEME_UNDEFINED, C_fix(0));
	((C_char *)fnbuf)[ n ] = '\0';
	return (C_char *)fnbuf;
}
#endif
